stages:
  - dozator-build

build:
  image: openjdk:17-oracle
  stage: dozator-build
  before_script:
    - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
    - chmod +x gradlew
  script:
    - ./gradlew -Pdocker.tag=$CI_COMMIT_TAG -Pregistry.user=$CI_REGISTRY_USER -Pregistry.password=$CI_REGISTRY_PASSWORD :dozator:dozator-api:jibGitlab
  only:
    - tags
