version: "3.9"

services:

  backend.dozator.io:
    container_name: dozator-backend
    image: dozator:latest
    restart: always
    depends_on:
      postgresql.dozator.io:
        condition: service_healthy
      mongodb.dozator.io:
        condition: service_healthy
    ports:
      - "8901:8901"
    networks:
      - dozator-network
    environment:
      - MONGO_USERNAME=dozator
      - MONGO_PASSWORD=secret
      - POSTGRES_USERNAME=dozator
      - POSTGRES_PASSWORD=secret
      - SPRINGPROFILES=default,actuator

  postgresql.dozator.io:
    container_name: dozator-postgresql
    image: postgres:11.9
    restart: always
    volumes:
      - static-content-postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5430:5432"
    networks:
      - dozator-network
    logging:
      driver: json-file
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=dozator
      - POSTGRES_USER=dozator
      - POSTGRES_PASSWORD=secret

  mongodb.dozator.io:
    container_name: dozator-mongodb
    image: mongo:5.0
    restart: always
    volumes:
      - ./docker/mongo/init_schema.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - static-content-mongodb:/data/db
    networks:
      - dozator-network
    logging:
      driver: json-file
    expose:
      - 27017
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dozator
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  static-content-postgresql:
  static-content-mongodb:

networks:
  dozator-network:
    driver: bridge
