package io.dozator.domain.dispenser.childCalculator.datas.height.girl

import io.dozator.domain.dispenser.childCalculator.datas.child.ReferenceData

class GirlHeightReferenceData (height: Double) : ReferenceData() {
    init {
        references["0.0.0"] = Girl0_0_0ChildListHeight(height)
        references["0.0.1"] = Girl0_0_1ChildListHeight(height)
        references["0.0.2"] = Girl0_0_2ChildListHeight(height)
        references["0.0.3"] = Girl0_0_3ChildListHeight(height)
        references["0.0.4"] = Girl0_0_4ChildListHeight(height)
        references["0.0.5"] = Girl0_0_5ChildListHeight(height)
        references["0.0.6"] = Girl0_0_6ChildListHeight(height)
        references["0.0.7"] = Girl0_0_7ChildListHeight(height)
        references["0.0.8"] = Girl0_0_8ChildListHeight(height)
        references["0.0.9"] = Girl0_0_9ChildListHeight(height)
        references["0.0.10"] = Girl0_0_10ChildListHeight(height)
        references["0.0.11"] = Girl0_0_11ChildListHeight(height)
        references["0.0.12"] = Girl0_0_12ChildListHeight(height)
        references["0.0.13"] = Girl0_0_13ChildListHeight(height)
        references["0.3"] = Girl0_3ChildListHeight(height)
        references["0.4"] = Girl0_4ChildListHeight(height)
        references["0.5"] = Girl0_5ChildListHeight(height)
        references["0.6"] = Girl0_6ChildListHeight(height)
        references["0.7"] = Girl0_7ChildListHeight(height)
        references["0.8"] = Girl0_8ChildListHeight(height)
        references["0.9"] = Girl0_9ChildListHeight(height)
        references["0.10"] = Girl0_10ChildListHeight(height)
        references["0.11"] = Girl0_11ChildListHeight(height)
        references["1.0"] = Girl1_0ChildListHeight(height)
        references["1.1"] = Girl1_1ChildListHeight(height)
        references["1.2"] = Girl1_2ChildListHeight(height)
        references["1.3"] = Girl1_3ChildListHeight(height)
        references["1.4"] = Girl1_4ChildListHeight(height)
        references["1.5"] = Girl1_5ChildListHeight(height)
        references["1.6"] = Girl1_6ChildListHeight(height)
        references["1.7"] = Girl1_7ChildListHeight(height)
        references["1.8"] = Girl1_8ChildListHeight(height)
        references["1.9"] = Girl1_9ChildListHeight(height)
        references["1.10"] = Girl1_10ChildListHeight(height)
        references["1.11"] = Girl1_11ChildListHeight(height)
        references["2.0"] = Girl2_0ChildListHeight(height)
        references["2.1"] = Girl2_1ChildListHeight(height)
        references["2.2"] = Girl2_2ChildListHeight(height)
        references["2.3"] = Girl2_3ChildListHeight(height)
        references["2.4"] = Girl2_4ChildListHeight(height)
        references["2.5"] = Girl2_5ChildListHeight(height)
        references["2.6"] = Girl2_6ChildListHeight(height)
        references["2.7"] = Girl2_7ChildListHeight(height)
        references["2.8"] = Girl2_8ChildListHeight(height)
        references["2.9"] = Girl2_9ChildListHeight(height)
        references["2.10"] = Girl2_10ChildListHeight(height)
        references["2.11"] = Girl2_11ChildListHeight(height)
        references["3.0"] = Girl3_0ChildListHeight(height)
        references["3.1"] = Girl3_1ChildListHeight(height)
        references["3.2"] = Girl3_2ChildListHeight(height)
        references["3.3"] = Girl3_3ChildListHeight(height)
        references["3.4"] = Girl3_4ChildListHeight(height)
        references["3.5"] = Girl3_5ChildListHeight(height)
        references["3.6"] = Girl3_6ChildListHeight(height)
        references["3.7"] = Girl3_7ChildListHeight(height)
        references["3.8"] = Girl3_8ChildListHeight(height)
        references["3.9"] = Girl3_9ChildListHeight(height)
        references["3.10"] = Girl3_10ChildListHeight(height)
        references["3.11"] = Girl3_11ChildListHeight(height)
        references["4.0"] = Girl4_0ChildListHeight(height)
        references["4.1"] = Girl4_1ChildListHeight(height)
        references["4.2"] = Girl4_2ChildListHeight(height)
        references["4.3"] = Girl4_3ChildListHeight(height)
        references["4.4"] = Girl4_4ChildListHeight(height)
        references["4.5"] = Girl4_5ChildListHeight(height)
        references["4.6"] = Girl4_6ChildListHeight(height)
        references["4.7"] = Girl4_7ChildListHeight(height)
        references["4.8"] = Girl4_8ChildListHeight(height)
        references["4.9"] = Girl4_9ChildListHeight(height)
        references["4.10"] = Girl4_10ChildListHeight(height)
        references["4.11"] = Girl4_11ChildListHeight(height)
        references["5.0"] = Girl5_0ChildListHeight(height)
    }
}