logging:
  level:
    io.dozator: DEBUG
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type: DEBUG
#    liquibase.exception: DEBUG
#    java.sql: DEBUG
    ROOT: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5132/dozator?rewriteBatchedStatements=true&assumeMinServerVersion=9.0
    username: dozator
    password: secret
  liquibase:
    user: dozator
    password: secret
    enabled: true
    drop-first: false
  data:
    mongodb:
      username: dozator
      password: secret
      host: localhost
      port: 26017
      database: dozator

management:
  endpoint:
    health:
      enabled: false
