package io.dozator.domain.dispenser.childCalculator.datas.weight.girl

import io.dozator.domain.dispenser.childCalculator.datas.child.ReferenceData
import io.dozator.domain.dispenser.childCalculator.datas.weight.girl.Girl0_0_10ChildListWeight

class GirlWeightReferenceData(weight: Double) : ReferenceData() {
    init {
        references["0.0.0"] = Girl0_0_0ChildListWeight(weight)
        references["0.0.1"] = Girl0_0_1ChildListWeight(weight)
        references["0.0.2"] = Girl0_0_2ChildListWeight(weight)
        references["0.0.3"] = Girl0_0_3ChildListWeight(weight)
        references["0.0.4"] = Girl0_0_4ChildListWeight(weight)
        references["0.0.5"] = Girl0_0_5ChildListWeight(weight)
        references["0.0.6"] = Girl0_0_6ChildListWeight(weight)
        references["0.0.7"] = Girl0_0_7ChildListWeight(weight)
        references["0.0.8"] = Girl0_0_8ChildListWeight(weight)
        references["0.0.9"] = Girl0_0_9ChildListWeight(weight)
        references["0.0.10"] = Girl0_0_10ChildListWeight(weight)
        references["0.0.11"] = Girl0_0_11ChildListWeight(weight)
        references["0.0.12"] = Girl0_0_12ChildListWeight(weight)
        references["0.0.13"] = Girl0_0_13ChildListWeight(weight)
        references["0.3"] = Girl0_3ChildListWeight(weight)
        references["0.4"] = Girl0_4ChildListWeight(weight)
        references["0.5"] = Girl0_5ChildListWeight(weight)
        references["0.6"] = Girl0_6ChildListWeight(weight)
        references["0.7"] = Girl0_7ChildListWeight(weight)
        references["0.8"] = Girl0_8ChildListWeight(weight)
        references["0.9"] = Girl0_9ChildListWeight(weight)
        references["0.10"] = Girl0_10ChildListWeight(weight)
        references["0.11"] = Girl0_11ChildListWeight(weight)
        references["1.0"] = Girl1_0ChildListWeight(weight)
        references["1.1"] = Girl1_1ChildListWeight(weight)
        references["1.2"] = Girl1_2ChildListWeight(weight)
        references["1.3"] = Girl1_3ChildListWeight(weight)
        references["1.4"] = Girl1_4ChildListWeight(weight)
        references["1.5"] = Girl1_5ChildListWeight(weight)
        references["1.6"] = Girl1_6ChildListWeight(weight)
        references["1.7"] = Girl1_7ChildListWeight(weight)
        references["1.8"] = Girl1_8ChildListWeight(weight)
        references["1.9"] = Girl1_9ChildListWeight(weight)
        references["1.10"] = Girl1_10ChildListWeight(weight)
        references["1.11"] = Girl1_11ChildListWeight(weight)
        references["2.0"] = Girl2_0ChildListWeight(weight)
        references["2.1"] = Girl2_1ChildListWeight(weight)
        references["2.2"] = Girl2_2ChildListWeight(weight)
        references["2.3"] = Girl2_3ChildListWeight(weight)
        references["2.4"] = Girl2_4ChildListWeight(weight)
        references["2.5"] = Girl2_5ChildListWeight(weight)
        references["2.6"] = Girl2_6ChildListWeight(weight)
        references["2.7"] = Girl2_7ChildListWeight(weight)
        references["2.8"] = Girl2_8ChildListWeight(weight)
        references["2.9"] = Girl2_9ChildListWeight(weight)
        references["2.10"] = Girl2_10ChildListWeight(weight)
        references["2.11"] = Girl2_11ChildListWeight(weight)
        references["3.0"] = Girl3_0ChildListWeight(weight)
        references["3.1"] = Girl3_1ChildListWeight(weight)
        references["3.2"] = Girl3_2ChildListWeight(weight)
        references["3.3"] = Girl3_3ChildListWeight(weight)
        references["3.4"] = Girl3_4ChildListWeight(weight)
        references["3.5"] = Girl3_5ChildListWeight(weight)
        references["3.6"] = Girl3_6ChildListWeight(weight)
        references["3.7"] = Girl3_7ChildListWeight(weight)
        references["3.8"] = Girl3_8ChildListWeight(weight)
        references["3.9"] = Girl3_9ChildListWeight(weight)
        references["3.10"] = Girl3_10ChildListWeight(weight)
        references["3.11"] = Girl3_11ChildListWeight(weight)
        references["4.0"] = Girl4_0ChildListWeight(weight)
        references["4.1"] = Girl4_1ChildListWeight(weight)
        references["4.2"] = Girl4_2ChildListWeight(weight)
        references["4.3"] = Girl4_3ChildListWeight(weight)
        references["4.4"] = Girl4_4ChildListWeight(weight)
        references["4.5"] = Girl4_5ChildListWeight(weight)
        references["4.6"] = Girl4_6ChildListWeight(weight)
        references["4.7"] = Girl4_7ChildListWeight(weight)
        references["4.8"] = Girl4_8ChildListWeight(weight)
        references["4.9"] = Girl4_9ChildListWeight(weight)
        references["4.10"] = Girl4_10ChildListWeight(weight)
        references["4.11"] = Girl4_11ChildListWeight(weight)
        references["5.0"] = Girl5_0ChildListWeight(weight)
    }
}