package io.dozator.domain.dispenser.childCalculator.datas.headСircumference.girl

import io.dozator.domain.dispenser.childCalculator.datas.child.ReferenceData

class GirlHeadCircReferenceData(headCirc: Double) : ReferenceData() {
    init {
        references["0.0.0"] = Girl0_0_0ChildListHeadCirc(headCirc)
        references["0.0.1"] = Girl0_0_1ChildListHeadCirc(headCirc)
        references["0.0.2"] = Girl0_0_2ChildListHeadCirc(headCirc)
        references["0.0.3"] = Girl0_0_3ChildListHeadCirc(headCirc)
        references["0.0.4"] = Girl0_0_4ChildListHeadCirc(headCirc)
        references["0.0.5"] = Girl0_0_5ChildListHeadCirc(headCirc)
        references["0.0.6"] = Girl0_0_6ChildListHeadCirc(headCirc)
        references["0.0.7"] = Girl0_0_7ChildListHeadCirc(headCirc)
        references["0.0.8"] = Girl0_0_8ChildListHeadCirc(headCirc)
        references["0.0.9"] = Girl0_0_9ChildListHeadCirc(headCirc)
        references["0.0.10"] = Girl0_0_10ChildListHeadCirc(headCirc)
        references["0.0.11"] = Girl0_0_11ChildListHeadCirc(headCirc)
        references["0.0.12"] = Girl0_0_12ChildListHeadCirc(headCirc)
        references["0.0.13"] = Girl0_0_13ChildListHeadCirc(headCirc)
        references["0.3"] = Girl0_3ChildListHeadCirc(headCirc)
        references["0.4"] = Girl0_4ChildListHeadCirc(headCirc)
        references["0.5"] = Girl0_5ChildListHeadCirc(headCirc)
        references["0.6"] = Girl0_6ChildListHeadCirc(headCirc)
        references["0.7"] = Girl0_7ChildListHeadCirc(headCirc)
        references["0.8"] = Girl0_8ChildListHeadCirc(headCirc)
        references["0.9"] = Girl0_9ChildListHeadCirc(headCirc)
        references["0.10"] = Girl0_10ChildListHeadCirc(headCirc)
        references["0.11"] = Girl0_11ChildListHeadCirc(headCirc)
        references["1.0"] = Girl1_0ChildListHeadCirc(headCirc)
        references["1.1"] = Girl1_1ChildListHeadCirc(headCirc)
        references["1.2"] = Girl1_2ChildListHeadCirc(headCirc)
        references["1.3"] = Girl1_3ChildListHeadCirc(headCirc)
        references["1.4"] = Girl1_4ChildListHeadCirc(headCirc)
        references["1.5"] = Girl1_5ChildListHeadCirc(headCirc)
        references["1.6"] = Girl1_6ChildListHeadCirc(headCirc)
        references["1.7"] = Girl1_7ChildListHeadCirc(headCirc)
        references["1.8"] = Girl1_8ChildListHeadCirc(headCirc)
        references["1.9"] = Girl1_9ChildListHeadCirc(headCirc)
        references["1.10"] = Girl1_10ChildListHeadCirc(headCirc)
        references["1.11"] = Girl1_11ChildListHeadCirc(headCirc)
        references["2.0"] = Girl2_0ChildListHeadCirc(headCirc)
        references["2.1"] = Girl2_1ChildListHeadCirc(headCirc)
        references["2.2"] = Girl2_2ChildListHeadCirc(headCirc)
        references["2.3"] = Girl2_3ChildListHeadCirc(headCirc)
        references["2.4"] = Girl2_4ChildListHeadCirc(headCirc)
        references["2.5"] = Girl2_5ChildListHeadCirc(headCirc)
        references["2.6"] = Girl2_6ChildListHeadCirc(headCirc)
        references["2.7"] = Girl2_7ChildListHeadCirc(headCirc)
        references["2.8"] = Girl2_8ChildListHeadCirc(headCirc)
        references["2.9"] = Girl2_9ChildListHeadCirc(headCirc)
        references["2.10"] = Girl2_10ChildListHeadCirc(headCirc)
        references["2.11"] = Girl2_11ChildListHeadCirc(headCirc)
        references["3.0"] = Girl3_0ChildListHeadCirc(headCirc)
        references["3.1"] = Girl3_1ChildListHeadCirc(headCirc)
        references["3.2"] = Girl3_2ChildListHeadCirc(headCirc)
        references["3.3"] = Girl3_3ChildListHeadCirc(headCirc)
        references["3.4"] = Girl3_4ChildListHeadCirc(headCirc)
        references["3.5"] = Girl3_5ChildListHeadCirc(headCirc)
        references["3.6"] = Girl3_6ChildListHeadCirc(headCirc)
        references["3.7"] = Girl3_7ChildListHeadCirc(headCirc)
        references["3.8"] = Girl3_8ChildListHeadCirc(headCirc)
        references["3.9"] = Girl3_9ChildListHeadCirc(headCirc)
        references["3.10"] = Girl3_10ChildListHeadCirc(headCirc)
        references["3.11"] = Girl3_11ChildListHeadCirc(headCirc)
        references["4.0"] = Girl4_0ChildListHeadCirc(headCirc)
        references["4.1"] = Girl4_1ChildListHeadCirc(headCirc)
        references["4.2"] = Girl4_2ChildListHeadCirc(headCirc)
        references["4.3"] = Girl4_3ChildListHeadCirc(headCirc)
        references["4.4"] = Girl4_4ChildListHeadCirc(headCirc)
        references["4.5"] = Girl4_5ChildListHeadCirc(headCirc)
        references["4.6"] = Girl4_6ChildListHeadCirc(headCirc)
        references["4.7"] = Girl4_7ChildListHeadCirc(headCirc)
        references["4.8"] = Girl4_8ChildListHeadCirc(headCirc)
        references["4.9"] = Girl4_9ChildListHeadCirc(headCirc)
        references["4.10"] = Girl4_10ChildListHeadCirc(headCirc)
        references["4.11"] = Girl4_11ChildListHeadCirc(headCirc)
        references["5.0"] = Girl5_0ChildListHeadCirc(headCirc)
    }
}