package io.dozator.domain.dispenser

enum class DispenserType {
    ELIQUIS_NVAF,
    ELIQUIS_JOINT,
    ELIQUIS_DVTPE,

    PRADAXA_NVAF,
    PRADAXA_DVTPE,

    XARELTO_NVAF,
    XARELTO_DVTPE,

    WARFARIN_NVAF_DOSE_TITRATION,
    WARFARIN_NVAF_START_OF_THERAPY,

    NSAID_MELOXICAM,
    NSAID_DICLOFENAC,
    NSAID_CELECOXIB,

    FRAXIPARINE_GSI,
    FRAXIPARINE_OI,
    FRAXIPARINE_ATP,
    FRAXIPARINE_DVTPE,
    FRAXIPARINE_H,
    FRAXIPARINE_UAMI,

    CLEXANE_BR,
    CLEXANE_DVT,
    CLEXANE_H,
    CLEXANE_MI_WITH_STE,
    CLEXANE_MI_WITHOUT_STE,
    CLEXANE_SI,

    SUBSTITUTE_WARFARIN_OAC,
    SUBSTITUTE_ELIQUIS_WARFARIN,
    SUBSTITUTE_PRADAXA_WARFARIN,
    SUBSTITUTE_XARELTO_WARFARIN,
    SUBSTITUTE_OAC_OAC,

    GFR_CKDEPI,
    GFR_MDRD,
    GFR_COCKCROFT_GAULT,
    GFR_SCHWARTZ,

    CARBAMAZEPINE_EPILEPSY_DOSE_TITRATION_FOR_ADULTS,
    CARBAMAZEPINE_EPILEPSY_DOSE_TITRATION_FOR_CHILDREN,
    CARBAMAZEPINE_EPILEPSY_THERAPY_START_FOR_ADULTS,
    CARBAMAZEPINE_EPILEPSY_THERAPY_START_FOR_CHILDREN,
    CARBAMAZEPINE_NEURALGIA_DOSE_TITRATION,
    CARBAMAZEPINE_NEURALGIA_THERAPY_START,

    VALPROIC_ACID_THERAPY_START_FOR_CHILDREN,
    VALPROIC_ACID_THERAPY_START_FOR_ADULTS,
    VALPROIC_ACID_DOSE_TITRATION_FOR_CHILDREN,
    VALPROIC_ACID_DOSE_TITRATION_FOR_ADULTS,

    MOXIFLOXACIN,

    TELAVANCIN,

    RIVASTIGMINE_THERAPY_START,
    RIVASTIGMINE_DOSE_TITRATION,

    MEMANTINE_THERAPY_START,
    MEMANTINE_DOSE_TITRATION,

    DONEPEZIL_THERAPY_START,
    DONEPEZIL_DOSE_TITRATION,

    GALANTAMINE_THERAPY_START,
    GALANTAMINE_DOSE_TITRATION,

    FEBUXOSTAT_THERAPY_START,
    FEBUXOSTAT_DOSE_TITRATION,
    FEBUXOSTAT_EXACERBATION,

    LAXATIVE_BISACODYL_CONSTIPATION,
    LAXATIVE_BISACODYL_SURGERY,
    LAXATIVE_BISACODYL_EXAMINATION,
    LAXATIVE_PICOSULFATE_CONSTIPATION,
    LAXATIVE_PICOSULFATE_SURGERY,
    LAXATIVE_PICOSULFATE_EXAMINATION,

    LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_CHILD,
    LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_TEEN,
    LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_ADULT,
    LAMOTRIGINE_MONOTHERAPY_START_CHILD,
    LAMOTRIGINE_MONOTHERAPY_START_TEEN,
    LAMOTRIGINE_MONOTHERAPY_START_ADULT,
    LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_CHILD,
    LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_TEEN,
    LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_ADULT,
    LAMOTRIGINE_COMBINED_THERAPY_START_CHILD,
    LAMOTRIGINE_COMBINED_THERAPY_START_TEEN,
    LAMOTRIGINE_COMBINED_THERAPY_START_ADULT,

    OXCARBAZEPINE_THERAPY_START_CHILD,
    OXCARBAZEPINE_THERAPY_START_ADULT,
    OXCARBAZEPINE_DOSE_TITRATION_CHILD,
    OXCARBAZEPINE_DOSE_TITRATION_ADULT,

    LEVODOPA_BENSERAZIDE_THERAPY_START,
    LEVODOPA_BENSERAZIDE_DOSE_TITRATION,

    LEVODOPA_CARBIDOPA_THERAPY_START,
    LEVODOPA_CARBIDOPA_DOSE_TITRATION,

    CHOLECALCIFEROL_DEFICIENCY_TREATMENT,
    CHOLECALCIFEROL_DEFICIENCY_PREVENTION,
    CHOLECALCIFEROL_RICKETS_TREATMENT,
    CHOLECALCIFEROL_RICKETS_PREVENTION,
    CHOLECALCIFEROL_OSTEOPOROSIS_TREATMENT,
    CHOLECALCIFEROL_HYPOPARATHYROIDISM_TREATMENT,

    VANCOMYCIN_ADULT,
    VANCOMYCIN_CHILD,

    CHAD2DS2VASC,
    HASBLED,

    VTEC,

    BODY_AREA,

    SOLUTION_MASS_CALCULATION,
    SOLUTION_CONCENTRATION_CALCULATION,
    SOLUTION_VOLUME_CALCULATION,

    GCS_CONVERTER_BY_DRUG,
    GCS_CONVERTER_BY_WEIGHT,

    GOUCKE,

    IRON_ORALLY,
    IRON_PARENTERALLY,

    MMSE,
    GERONTONET,

    LEVOTHYROXINE_PRIMARY_HYPOTHYROIDISM_ADULT,
    LEVOTHYROXINE_SECONDARY_HYPOTHYROIDISM_ADULT,
    LEVOTHYROXINE_CONGENITAL_HYPOTHYROIDISM_CHILD,

    RISPERIDONE_SCHIZOPHRENIA,
    RISPERIDONE_BAD,
    RISPERIDONE_AGRESSION_MR,
    RISPERIDONE_AGRESSION_DEMENTIA,
    ;



    object Constants {
        const val ELIQUIS_NVAF_VALUE = "ELIQUIS_NVAF"
        const val ELIQUIS_JOINT_VALUE = "ELIQUIS_JOINT"
        const val ELIQUIS_DVTPE_VALUE = "ELIQUIS_DVTPE"

        const val PRADAXA_NVAF_VALUE = "PRADAXA_NVAF"
        const val PRADAXA_DVTPE_VALUE = "PRADAXA_DVTPE"

        const val XARELTO_NVAF_VALUE = "XARELTO_NVAF"
        const val XARELTO_DVTPE_VALUE = "XARELTO_DVTPE"

        const val WARFARIN_NVAF_DOSE_TITRATION_VALUE = "WARFARIN_NVAF_DOSE_TITRATION"
        const val WARFARIN_NVAF_START_OF_THERAPY_VALUE = "WARFARIN_NVAF_START_OF_THERAPY"

        const val NSAID_MELOXICAM_VALUE = "NSAID_MELOXICAM"
        const val NSAID_DICLOFENAC_VALUE = "NSAID_DICLOFENAC"
        const val NSAID_CELECOXIB_VALUE = "NSAID_CELECOXIB"

        const val FRAXIPARINE_GSI_VALUE = "FRAXIPARINE_GSI"
        const val FRAXIPARINE_OI_VALUE = "FRAXIPARINE_OI"
        const val FRAXIPARINE_ATP_VALUE = "FRAXIPARINE_ATP"
        const val FRAXIPARINE_DVTPE_VALUE = "FRAXIPARINE_DVTPE"
        const val FRAXIPARINE_H_VALUE = "FRAXIPARINE_H"
        const val FRAXIPARINE_UAMI_VALUE = "FRAXIPARINE_UAMI"

        const val CLEXANE_BR_VALUE = "CLEXANE_BR"
        const val CLEXANE_DVT_VALUE = "CLEXANE_DVT"
        const val CLEXANE_H_VALUE = "CLEXANE_H"
        const val CLEXANE_MI_WITH_STE_VALUE = "CLEXANE_MI_WITH_STE"
        const val CLEXANE_MI_WITHOUT_STE_VALUE = "CLEXANE_MI_WITHOUT_STE"
        const val CLEXANE_SI_VALUE = "CLEXANE_SI"

        const val SUBSTITUTE_WARFARIN_OAC_VALUE = "SUBSTITUTE_WARFARIN_OAC"
        const val SUBSTITUTE_ELIQUIS_WARFARIN_VALUE = "SUBSTITUTE_ELIQUIS_WARFARIN"
        const val SUBSTITUTE_PRADAXA_WARFARIN_VALUE = "SUBSTITUTE_PRADAXA_WARFARIN"
        const val SUBSTITUTE_XARELTO_WARFARIN_VALUE = "SUBSTITUTE_XARELTO_WARFARIN"
        const val SUBSTITUTE_OAC_OAC_VALUE = "SUBSTITUTE_OAC_OAC"

        const val GFR_CKDEPI_VALUE = "GFR_CKDEPI"
        const val GFR_MDRD_VALUE = "GFR_MDRD"
        const val GFR_COCKCROFT_GAULT_VALUE = "GFR_COCKCROFT_GAULT"
        const val GFR_SCHWARTZ_VALUE = "GFR_SCHWARTZ"

        const val CARBAMAZEPINE_EPILEPSY_DOSE_TITRATION_FOR_ADULTS_VALUE = "CARBAMAZEPINE_EPILEPSY_DOSE_TITRATION_FOR_ADULTS"
        const val CARBAMAZEPINE_EPILEPSY_DOSE_TITRATION_FOR_CHILDREN_VALUE = "CARBAMAZEPINE_EPILEPSY_DOSE_TITRATION_FOR_CHILDREN"
        const val CARBAMAZEPINE_EPILEPSY_THERAPY_START_FOR_ADULTS_VALUE = "CARBAMAZEPINE_EPILEPSY_THERAPY_START_FOR_ADULTS"
        const val CARBAMAZEPINE_EPILEPSY_THERAPY_START_FOR_CHILDREN_VALUE = "CARBAMAZEPINE_EPILEPSY_THERAPY_START_FOR_CHILDREN"
        const val CARBAMAZEPINE_NEURALGIA_DOSE_TITRATION_VALUE = "CARBAMAZEPINE_NEURALGIA_DOSE_TITRATION"
        const val CARBAMAZEPINE_NEURALGIA_THERAPY_START_VALUE = "CARBAMAZEPINE_NEURALGIA_THERAPY_START"

        const val VALPROIC_ACID_THERAPY_START_FOR_CHILDREN_VALUE = "VALPROIC_ACID_THERAPY_START_FOR_CHILDREN"
        const val VALPROIC_ACID_THERAPY_START_FOR_ADULTS_VALUE = "VALPROIC_ACID_THERAPY_START_FOR_ADULTS"
        const val VALPROIC_ACID_DOSE_TITRATION_FOR_CHILDREN_VALUE = "VALPROIC_ACID_DOSE_TITRATION_FOR_CHILDREN"
        const val VALPROIC_ACID_DOSE_TITRATION_FOR_ADULTS_VALUE = "VALPROIC_ACID_DOSE_TITRATION_FOR_ADULTS"

        const val MOXIFLOXACIN_VALUE = "MOXIFLOXACIN"

        const val TELAVANCIN_VALUE = "TELAVANCIN"

        const val RIVASTIGMINE_THERAPY_START_VALUE = "RIVASTIGMINE_THERAPY_START"
        const val RIVASTIGMINE_DOSE_TITRATION_VALUE = "RIVASTIGMINE_DOSE_TITRATION"

        const val MEMANTINE_THERAPY_START_VALUE = "MEMANTINE_THERAPY_START"
        const val MEMANTINE_DOSE_TITRATION_VALUE = "MEMANTINE_DOSE_TITRATION"

        const val DONEPEZIL_THERAPY_START_VALUE = "DONEPEZIL_THERAPY_START"
        const val DONEPEZIL_DOSE_TITRATION_VALUE = "DONEPEZIL_DOSE_TITRATION"

        const val GALANTAMINE_THERAPY_START_VALUE = "GALANTAMINE_THERAPY_START"
        const val GALANTAMINE_DOSE_TITRATION_VALUE = "GALANTAMINE_DOSE_TITRATION"

        const val FEBUXOSTAT_THERAPY_START_VALUE = "FEBUXOSTAT_THERAPY_START"
        const val FEBUXOSTAT_DOSE_TITRATION_VALUE = "FEBUXOSTAT_DOSE_TITRATION"
        const val FEBUXOSTAT_EXACERBATION_VALUE = "FEBUXOSTAT_EXACERBATION"

        const val LAXATIVE_BISACODYL_CONSTIPATION_VALUE = "LAXATIVE_BISACODYL_CONSTIPATION"
        const val LAXATIVE_BISACODYL_SURGERY_VALUE = "LAXATIVE_BISACODYL_SURGERY"
        const val LAXATIVE_BISACODYL_EXAMINATION_VALUE = "LAXATIVE_BISACODYL_EXAMINATION"
        const val LAXATIVE_PICOSULFATE_CONSTIPATION_VALUE = "LAXATIVE_PICOSULFATE_CONSTIPATION"
        const val LAXATIVE_PICOSULFATE_SURGERY_VALUE = "LAXATIVE_PICOSULFATE_SURGERY"
        const val LAXATIVE_PICOSULFATE_EXAMINATION_VALUE = "LAXATIVE_PICOSULFATE_EXAMINATION"

        const val LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_CHILD_VALUE = "LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_CHILD"
        const val LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_TEEN_VALUE = "LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_TEEN"
        const val LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_ADULT_VALUE = "LAMOTRIGINE_MONOTHERAPY_DOSE_TITRATION_ADULT"
        const val LAMOTRIGINE_MONOTHERAPY_START_CHILD_VALUE = "LAMOTRIGINE_MONOTHERAPY_START_CHILD"
        const val LAMOTRIGINE_MONOTHERAPY_START_TEEN_VALUE = "LAMOTRIGINE_MONOTHERAPY_START_TEEN"
        const val LAMOTRIGINE_MONOTHERAPY_START_ADULT_VALUE = "LAMOTRIGINE_MONOTHERAPY_START_ADULT"
        const val LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_CHILD_VALUE = "LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_CHILD"
        const val LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_TEEN_VALUE = "LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_TEEN"
        const val LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_ADULT_VALUE = "LAMOTRIGINE_COMBINED_THERAPY_DOSE_TITRATION_ADULT"
        const val LAMOTRIGINE_COMBINED_THERAPY_START_CHILD_VALUE = "LAMOTRIGINE_COMBINED_THERAPY_START_CHILD"
        const val LAMOTRIGINE_COMBINED_THERAPY_START_TEEN_VALUE = "LAMOTRIGINE_COMBINED_THERAPY_START_TEEN"
        const val LAMOTRIGINE_COMBINED_THERAPY_START_ADULT_VALUE = "LAMOTRIGINE_COMBINED_THERAPY_START_ADULT"

        const val OXCARBAZEPINE_THERAPY_START_CHILD_VALUE = "OXCARBAZEPINE_THERAPY_START_CHILD"
        const val OXCARBAZEPINE_THERAPY_START_ADULT_VALUE = "OXCARBAZEPINE_THERAPY_START_ADULT"
        const val OXCARBAZEPINE_DOSE_TITRATION_CHILD_VALUE = "OXCARBAZEPINE_DOSE_TITRATION_CHILD"
        const val OXCARBAZEPINE_DOSE_TITRATION_ADULT_VALUE = "OXCARBAZEPINE_DOSE_TITRATION_ADULT"

        const val LEVODOPA_BENSERAZIDE_THERAPY_START_VALUE = "LEVODOPA_BENSERAZIDE_THERAPY_START"
        const val LEVODOPA_BENSERAZIDE_DOSE_TITRATION_VALUE = "LEVODOPA_BENSERAZIDE_DOSE_TITRATION"

        const val LEVODOPA_CARBIDOPA_THERAPY_START_VALUE = "LEVODOPA_CARBIDOPA_THERAPY_START"
        const val LEVODOPA_CARBIDOPA_DOSE_TITRATION_VALUE = "LEVODOPA_CARBIDOPA_DOSE_TITRATION"

        const val CHOLECALCIFEROL_DEFICIENCY_TREATMENT_VALUE = "CHOLECALCIFEROL_DEFICIENCY_TREATMENT"
        const val CHOLECALCIFEROL_DEFICIENCY_PREVENTION_VALUE = "CHOLECALCIFEROL_DEFICIENCY_PREVENTION"
        const val CHOLECALCIFEROL_RICKETS_TREATMENT_VALUE = "CHOLECALCIFEROL_RICKETS_TREATMENT"
        const val CHOLECALCIFEROL_RICKETS_PREVENTION_VALUE = "CHOLECALCIFEROL_RICKETS_PREVENTION"
        const val CHOLECALCIFEROL_OSTEOPOROSIS_TREATMENT_VALUE = "CHOLECALCIFEROL_OSTEOPOROSIS_TREATMENT"
        const val CHOLECALCIFEROL_HYPOPARATHYROIDISM_TREATMENT_VALUE = "CHOLECALCIFEROL_HYPOPARATHYROIDISM_TREATMENT"

        const val VANCOMYCIN_ADULT_VALUE = "VANCOMYCIN_ADULT"
        const val VANCOMYCIN_CHILD_VALUE = "VANCOMYCIN_CHILD"

        const val CHAD2DS2VASC_VALUE = "CHAD2DS2VASC"
        const val HASBLED_VALUE = "HASBLED"

        const val VTEC_VALUE = "VTEC"

        const val BODY_AREA_VALUE = "BODY_AREA"

        const val SOLUTION_MASS_CALCULATION_VALUE = "SOLUTION_MASS_CALCULATION"
        const val SOLUTION_CONCENTRATION_CALCULATION_VALUE = "SOLUTION_CONCENTRATION_CALCULATION"
        const val SOLUTION_VOLUME_CALCULATION_VALUE = "SOLUTION_VOLUME_CALCULATION"

        const val GCS_CONVERTER_BY_DRUG_VALUE = "GCS_CONVERTER_BY_DRUG"
        const val GCS_CONVERTER_BY_WEIGHT_VALUE = "GCS_CONVERTER_BY_WEIGHT"

        const val GOUCKE_VALUE = "GOUCKE"

        const val IRON_ORALLY_VALUE = "IRON_ORALLY"
        const val IRON_PARENTERALLY_VALUE = "IRON_PARENTERALLY"

        const val MMSE_VALUE = "MMSE"
        const val GERONTONET_VALUE = "GERONTONET"

        const val LEVOTHYROXINE_PRIMARY_HYPOTHYROIDISM_ADULT_VALUE = "LEVOTHYROXINE_PRIMARY_HYPOTHYROIDISM_ADULT"
        const val LEVOTHYROXINE_SECONDARY_HYPOTHYROIDISM_ADULT_VALUE = "LEVOTHYROXINE_SECONDARY_HYPOTHYROIDISM_ADULT"
        const val LEVOTHYROXINE_CONGENITAL_HYPOTHYROIDISM_CHILD_VALUE = "LEVOTHYROXINE_CONGENITAL_HYPOTHYROIDISM_CHILD"

        const val RISPERIDONE_SCHIZOPHRENIA_VALUE = "RISPERIDONE_SCHIZOPHRENIA"
        const val RISPERIDONE_BAD_VALUE = "RISPERIDONE_BAD"
        const val RISPERIDONE_AGRESSION_MR_VALUE = "RISPERIDONE_AGRESSION_MR"
        const val RISPERIDONE_AGRESSION_DEMENTIA_VALUE = "RISPERIDONE_AGRESSION_DEMENTIA"
    }
}
